version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_USERNAME=postgres.rdaafwjrkvgbxhqwaksm
      - DB_PASSWORD=t9CZWz8BF07GTGmN
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - PORT=3000
      - DATABASE_URL=mysql://freedb_test_db:s%J3uGJY!6C9HdJ@sql.freedb.tech:3306/freedb_leave_database
      - JWT_SECRET=secret
      - JWT_EXPIRATION=24h
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
